import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AppChrome from "../components/layout/AppChrome";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          className="flex min-h-screen flex-col bg-[var(--background)] text-[var(--foreground)]"
          style={{ backgroundImage: "var(--glow-gradient)" }}
        >
          <AppChrome>{children}</AppChrome>
        </div>
      </body>
    </html>
  );
}
